# Generated by Django 3.2.12 on 2022-02-25 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resume.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SkillTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField(blank=True, null=True)),
                ('cv', models.FileField(upload_to=resume.models.get_file_path)),
                ('general_tags', models.ManyToManyField(blank=True, to='resume.GeneralTags')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_reference', to=settings.AUTH_USER_MODEL)),
                ('skill_tags', models.ManyToManyField(blank=True, to='resume.SkillTags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
