# Generated by Django 3.2.12 on 2022-02-25 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0004_alter_resume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_reference', to=settings.AUTH_USER_MODEL),
        ),
    ]
